{{- if .Values.ingress.enabled -}}
{{- $fullName := include "nyan.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nyan.fullname" . }}
  labels:
    {{- include "nyan.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^({{ $ingressPath }})$ $1/ permanent;
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}/?(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port: 
                  number: {{ $svcPort }}
  {{- end }}
status:
  loadBalancer:
    ingress:
    - {}
{{- end }}
